name: split_bill
description: "help to split the bill"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
# state magange
  provider: ^6.1.1
# local storage
  hive: ^2.2.3
  hive_flutter: any
# Routing
  auto_route: ^7.8.4
# htpp
  # retrofit: ^4.0.3
# notification
  # fluttertoast: ^8.2.4
# splash screen
  # flutter_native_splash: ^2.3.6
# url 
  url_launcher: ^6.2.2



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any
  auto_route_generator: ^7.3.2
# Generates icons for android, ios, web, windows, macos 
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "path/to/image.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "path/to/image.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "path/to/image.png"

 
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700